<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2059" started-at="2016-11-24T10:33:47Z" finished-at="2016-11-24T10:33:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2059" started-at="2016-11-24T10:33:47Z" finished-at="2016-11-24T10:33:49Z">
      <class name="com.dji.itester.cases.NewTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.dji.itester.cases.NewTest@233c0b17]" name="beforeSuite" is-config="true" duration-ms="6" started-at="2016-11-24T18:33:47Z" finished-at="2016-11-24T18:33:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.dji.itester.cases.NewTest@233c0b17]" name="beforeTest" is-config="true" duration-ms="0" started-at="2016-11-24T18:33:47Z" finished-at="2016-11-24T18:33:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.dji.itester.cases.NewTest@233c0b17]" name="beforeClass" is-config="true" duration-ms="0" started-at="2016-11-24T18:33:47Z" finished-at="2016-11-24T18:33:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="test()[pri:0, instance:com.dji.itester.cases.NewTest@233c0b17]" name="test" duration-ms="2050" started-at="2016-11-24T18:33:47Z" finished-at="2016-11-24T18:33:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [{"status":0,"uid":"730650542689353728","token":"0a467776fd17484aaa5c482af1c0f36175423096","status_msg":"ok","avatar":"http://usa-test-sp.skypixel.com/user/charlie-ccc3968c-e907-4ace-975e-6bcfcdbd5af7/avatar/x128"}] but found [dsgfdfgdfsdfdgfdg]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [{"status":0,"uid":"730650542689353728","token":"0a467776fd17484aaa5c482af1c0f36175423096","status_msg":"ok","avatar":"http://usa-test-sp.skypixel.com/user/charlie-ccc3968c-e907-4ace-975e-6bcfcdbd5af7/avatar/x128"}] but found [dsgfdfgdfsdfdgfdg]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.dji.itester.cases.NewTest.test(NewTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.dji.itester.cases.NewTest@233c0b17]" name="afterClass" is-config="true" duration-ms="0" started-at="2016-11-24T18:33:49Z" finished-at="2016-11-24T18:33:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.dji.itester.cases.NewTest@233c0b17]" name="afterTest" is-config="true" duration-ms="0" started-at="2016-11-24T18:33:49Z" finished-at="2016-11-24T18:33:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="closeClient()[pri:0, instance:com.dji.itester.cases.NewTest@233c0b17]" name="closeClient" is-config="true" duration-ms="1" started-at="2016-11-24T18:33:49Z" finished-at="2016-11-24T18:33:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeClient -->
      </class> <!-- com.dji.itester.cases.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
