<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="charliechen" name="com.dji.itester.cases.NewTest" tests="1" failures="0" timestamp="24 Nov 2016 10:33:49 GMT" time="2.050" errors="1">
  <testcase name="test" time="2.050" classname="com.dji.itester.cases.NewTest">
    <error type="java.lang.AssertionError" message="expected [{&quot;status&quot;:0,&quot;uid&quot;:&quot;730650542689353728&quot;,&quot;token&quot;:&quot;0a467776fd17484aaa5c482af1c0f36175423096&quot;,&quot;status_msg&quot;:&quot;ok&quot;,&quot;avatar&quot;:&quot;http://usa-test-sp.skypixel.com/user/charlie-ccc3968c-e907-4ace-975e-6bcfcdbd5af7/avatar/x128&quot;}] but found [dsgfdfgdfsdfdgfdg]">
      <![CDATA[java.lang.AssertionError: expected [{"status":0,"uid":"730650542689353728","token":"0a467776fd17484aaa5c482af1c0f36175423096","status_msg":"ok","avatar":"http://usa-test-sp.skypixel.com/user/charlie-ccc3968c-e907-4ace-975e-6bcfcdbd5af7/avatar/x128"}] but found [dsgfdfgdfsdfdgfdg]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.dji.itester.cases.NewTest.test(NewTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test -->
</testsuite> <!-- com.dji.itester.cases.NewTest -->
